### ISSUE TITLE
java虚拟机 3.2 标记 - 整理的介绍好像不正确

### ISSUE THREAD

**Issue by librarysong** [frank-lam/fullstack-tutorial#19]

**Comment by frank-lam** [comment]
@librarysong 非常感谢你的问题，我也有段时间没有再看虚拟机这块了，如果有问题纠错非常欢迎贡献代码，我会把你的修改 merge 到我的仓库中。[【开源贡献】如何给我的仓库贡献？](https://github.com/frank-lam/2019_campus_apply/blob/master/notes/docs/%E5%A6%82%E4%BD%95%E7%BB%99%E6%88%91%E7%9A%84%E4%BB%93%E5%BA%93%E8%B4%A1%E7%8C%AE.md)
