### ISSUE TITLE
删除不必要的历史文件

### ISSUE THREAD

**Issue by si9ma** [frank-lam/fullstack-tutorial#29]
![xnip2019-01-30_20-39-58](https://user-images.githubusercontent.com/24809310/51981861-479fdc80-24cf-11e9-8adc-b14c7f74eab5.jpg)
我觉着可以把提交历史里面的这种类型的文件删除，其实也不大，强迫症😁，提个建议

**Comment by frank-lam** [comment]
@si9ma 哈哈好的呢，这两天我来个大整理下~
