### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by FaycalKhe** [frank-lam/fullstack-tutorial#41]
First of all, I would thank you for the content you are giving to developers.
I have just one request. Can you please provide an English version, I'd like to read more and google translate is not enough.
Thanks.

**Comment by frank-lam** [comment]
Thanks for your advice. For internationalization, English support is imperative. However, at present, my English ability is limited. If you are willing, welcome to join my open source team. @FaycalKhe

**Comment by FaycalKhe** [comment]
Thanks for the invitation @frank-lam, but my Chinese ability is limited too, otherwise I'll be very happy to help

**Comment by frank-lam** [comment]
I just graduated and entered the workplace. There are still many shortcomings in the face of the entire set of technologies in the background. I hope that with this repository, I can constantly improve my technology tree. I hope that one day I can really achieve full stack development.
If you have more skill tree, or may be you can pull request to my repository.
We can connect together by wechat: frank_lin5. @FaycalKhe

**Comment by frank-lam** [comment]
You can just add your skill tree document what you are good at, English is OK, than I will translate to Chinese. @FaycalKhe
